"""
Implements Old Persian Cuneiform converter.
"""

ALPHA_TO_OLDPERSIAN_CUNEIFORM = [
    (r"-", ""),
    (r"ahuramazda1", "𐏈"),
    (r"ahuramazda2", "𐏉"),
    (r"ahuramazda3", "𐏊"),
    (r"xshayathia", "𐏋"),
    (r"dahyaus1", "𐏌"),
    (r"dahyaus2", "𐏌"),
    (r"baga", "𐏎"),
    (r"bumis", "𐏏"),
    (r"mi", "𐎷"),
    (r"mu", "𐎸"),
    (r"ku", "𐎤"),
    (r"xi", "𐎧"),
    (r"gu", "𐎦"),
    (r"xu", "𐎧"),
    (r"ji", "𐎪"),
    (r"ti", "𐎫"),
    (r"tu", "𐎬"),
    (r"th", "𐎰"),
    (r"di", "𐎮"),
    (r"du", "𐎯"),
    (r"ni", "𐎴"),
    (r"nu", "𐎵"),
    (r"vi", "𐎻"),
    (r"ri", "𐎽"),
    (r"sh", "𐏁"),
    (r"a", "𐎠"),
    (r"i", "𐎡"),
    (r"u", "𐎢"),
    (r"k", "𐎣"),
    (r"x", "𐎧"),
    (r"g", "𐎥"),
    (r"c", "𐎨"),
    (r"ç", "𐏂"),
    (r"j", "𐎩"),
    (r"t", "𐎫"),
    (r"d", "𐎭"),
    (r"p", "𐎱"),
    (r"f", "𐎳"),
    (r"b", "𐎲"),
    (r"n", "𐎴"),
    (r"m", "𐎶"),
    (r"y", "𐎹"),
    (r"v", "𐎺"),
    (r"r", "𐎼"),
    (r"l", "𐎾"),
    (r"s", "𐎿"),
    (r"z", "𐏀"),
    (r"š", "𐏁"),
    (r"h", "𐏃")]
